[build-system]
requires = ["poetry_core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "ryoma-studio"
version = "0.0.1"
description = "Root project for Ryoma AI Platform"
authors = ["ryoma <contact@project-ryoma.com>"]
license = "Apache Software License 2.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
ryoma = {path = "./ryoma"}
ryoma_lab = {path = "./ryoma_lab"}

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
black = "^21.9b0"
isort = "^5.9.3"
mypy = "^0.910"
flake8 = "^3.9.2"
